export const mainCurrencies = [
  { currency: "CZK", title: "Czech Koruna" },
  { currency: "EUR", title: "Euro" },
  { currency: "UAH", title: "Ukrainian Hryvnia" },
  { currency: "KZT", title: "Kazakhstani Tenge" },
  { currency: "JPY", title: "Japanese Yen" },
  { currency: "GBP", title: "British Pound Sterling" },
  { currency: "AUD", title: "Australian Dollar" },
  { currency: "CAD", title: "Canadian Dollar" },
  { currency: "CHF", title: "Swiss Franc" },
  { currency: "CNY", title: "Chinese Yuan" },
  { currency: "SEK", title: "Swedish Krona" },
  { currency: "NZD", title: "New Zealand Dollar" },
];

export const cryptoCurrencies = [
  { currency: "BTC", title: "Bitcoin" },
  { currency: "ETH", title: "Ethereum" },
  { currency: "BNB", title: "Binance Coin" },
  { currency: "XRP", title: "XRP" },
  { currency: "DOGE", title: "Dogecoin" },
  { currency: "ADA", title: "Cardano" },
  { currency: "DOT", title: "Polkadot" },
  { currency: "LTC", title: "Litecoin" },
  { currency: "BCH", title: "Bitcoin Cash" },
  { currency: "LINK", title: "Chainlink" },
  { currency: "XLM", title: "Stellar" },
  { currency: "UNI", title: "Uniswap" },
  { currency: "USDC", title: "USD Coin" },
  { currency: "DASH", title: "Dash" },
  { currency: "XTZ", title: "Tezos" },
  { currency: "ATOM", title: "Cosmos" },
  { currency: "XEM", title: "NEM" },
  { currency: "VET", title: "VeChain" },
  { currency: "WBTC", title: "Wrapped Bitcoin" },
  { currency: "SOL", title: "Solana" },
];
